/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Friends": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "HabitsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ListeningHabits": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MusicMixerBackend": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}

import "sst"
export {}