import type { RecommendationTrack } from '@music-mixer/shared';
import { fetchWithRetry } from '../../utils/fetch';
import { SPOTIFY_API_BASE } from '../../config/spotify';
import { getValidAccessToken } from '../session/manager';

interface SpotifyCreatePlaylistResponse {
  id: string;
  external_urls: { spotify: string };
}

const TRACKS_PER_REQUEST = 100;

export async function exportPlaylistToSpotify(
  sessionId: string,
  tracks: RecommendationTrack[],
  name: string,
  isPublic: boolean,
): Promise<{ playlistUrl: string; playlistId: string }> {
  const accessToken = await getValidAccessToken(sessionId);
  if (!accessToken) throw new Error('Session expired');

  const createRes = await fetchWithRetry(`${SPOTIFY_API_BASE}/me/playlists`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name,
      description: 'Generated by MusicMixer — Taste Collision Engine',
      public: isPublic,
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.text();
    throw new Error(`Failed to create playlist: ${err}`);
  }

  const created = (await createRes.json()) as SpotifyCreatePlaylistResponse;
  const uris = tracks.map((t) => `spotify:track:${t.id}`);

  for (let i = 0; i < uris.length; i += TRACKS_PER_REQUEST) {
    const chunk = uris.slice(i, i + TRACKS_PER_REQUEST);
    const addRes = await fetchWithRetry(`${SPOTIFY_API_BASE}/playlists/${created.id}/items`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ uris: chunk }),
    });

    if (!addRes.ok) {
      const err = await addRes.text();
      throw new Error(`Failed to add tracks: ${err}`);
    }
  }

  return {
    playlistUrl: created.external_urls.spotify,
    playlistId: created.id,
  };
}
